trigger:
  branches:
    include:
      - main   # change if your branch is different

variables:
  ACR_NAME: youracrname   # your Azure Container Registry name
  IMAGE_NAME: flatris

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    displayName: 'Checkout repository'

  - task: Docker@2
    displayName: 'Build and push image to ACR'
    inputs:
      containerRegistry: 'AKS-ServiceConnection'  # name of your service connection
      repository: '$(IMAGE_NAME)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
