name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: latest
      - run: yarn --frozen-lockfile
      - run: yarn flow check
      - run: yarn lint
      - run: yarn test --maxWorkers=2
      - run: yarn test:visual:check
      - uses: actions/upload-artifact@v1
        with:
          name: snapshots
          path: web/__image_snapshots__
